version: "3"
services:
  smsgangapp:
    image: ghcr.io/Usmanbalogun044/smsgang:main
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./.env:/var/www/html/.env"
    networks:
      - app_smsgang
    depends_on:
      - smsgangdatabase
      - smsgangredis
    environment:
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=100M

  smsgangdatabase:
    image: "mysql/mysql-server:8.0"
    restart: always
    ports:
      - "${FORWARD_DB_PORT:-3311}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "smsgang-mysql:/var/lib/mysql"
    networks:
      - app_smsgang
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-p${DB_PASSWORD}"
      retries: 3
      timeout: 5s

  smsgangredis:
    image: "redis:alpine"
    restart: always
    ports:
      - "${FORWARD_REDIS_PORT:-6382}:6379"
    volumes:
      - "smsgang-redis:/data"
    networks:
      - app_smsgang
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
    command: redis-server --appendonly yes --replica-read-only no

  phpmyadmin:
    container_name: smsgangadmin
    image: phpmyadmin:apache
    restart: always
    ports:
      - 5001:80
    depends_on:
      - smsgangdatabase
    environment:
      PMA_HOST: smsgangdatabase
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
    networks:
      - app_smsgang

  dozzle:
    image: amir20/dozzle:latest
    restart: always
    ports:
      - "8086:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_smsgang

  nginx:
    image: nginx:1.25.1-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /data/certbot/www/:/var/www/certbot/
      - /data/certbot/letsencrypt/:/etc/letsencrypt/
      - ./server/default-production.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - smsgangapp
    networks:
      - app_smsgang

volumes:
  smsgang-mysql:
    driver: local
  smsgang-redis:
    driver: local

networks:
  app_smsgang:
    driver: bridge
